using System.Security.Cryptography;
using System.Text;
using Bitwyck.Core.Interfaces;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.Extensions.Logging;

namespace Bitwyck.Runtime.Lifecycle;

/// <summary>
/// Translates a successful <see cref="ToolChainTrace"/> into C# source code for
/// a new <see cref="ITool"/> that replays the original call sequence, then
/// compiles and loads that skill via <see cref="SkillCompiler"/>.
/// </summary>
public sealed class SkillSynthesizer : ISkillSynthesizer
{
    private readonly SkillCompiler _compiler;
    private readonly IToolRegistry _registry;
    private readonly ILogger<SkillSynthesizer> _logger;

    public SkillSynthesizer(
        SkillCompiler compiler,
        IToolRegistry registry,
        ILogger<SkillSynthesizer> logger)
    {
        _compiler = compiler;
        _registry = registry;
        _logger = logger;
    }

    // -------------------------------------------------------------------------
    // ISkillSynthesizer
    // -------------------------------------------------------------------------

    /// <inheritdoc/>
    public Task<SynthesizedSkill> SynthesizeAsync(
        ToolChainTrace trace,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(trace);

        var hashHex = ComputeGoalHash(trace.Goal);
        var toolName = $"synth_{hashHex}";
        var className = $"Synth_{hashHex}";
        var source = BuildSource(trace, hashHex, className, toolName);

        var skill = new SynthesizedSkill(
            SkillId: hashHex,
            SourceCode: source,
            ToolName: toolName,
            State: SkillLifecycleState.Proposed,
            CreatedAt: DateTimeOffset.UtcNow);

        _logger.LogInformation(
            "Synthesized skill '{ToolName}' ({Steps} steps) for goal: {Goal}",
            toolName, trace.Calls.Count, trace.Goal);

        return Task.FromResult(skill);
    }

    /// <inheritdoc/>
    public async Task<ITool?> CompileAndLoadAsync(
        SynthesizedSkill skill,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(skill);

        _logger.LogInformation(
            "Compiling skill '{ToolName}' (id={SkillId})…",
            skill.ToolName, skill.SkillId);

        var typeName = $"Synth_{skill.SkillId}";

        var (tool, diagnostics) = await _compiler.CompileToToolAsync(
            skill.SourceCode,
            typeName,
            _registry,
            ct);

        if (tool is null)
        {
            _logger.LogError(
                "Compilation failed for skill '{ToolName}'. {DiagCount} diagnostic(s).",
                skill.ToolName, diagnostics.Count);
            return null;
        }

        _registry.Register(tool);
        _logger.LogInformation(
            "Skill '{ToolName}' compiled and registered successfully.",
            skill.ToolName);

        return tool;
    }

    // -------------------------------------------------------------------------
    // Source generation
    // -------------------------------------------------------------------------

    private static string BuildSource(
        ToolChainTrace trace,
        string hashHex,
        string className,
        string toolName)
    {
        var sb = new StringBuilder();

        // File header
        sb.AppendLine($"// Auto-generated by SkillSynthesizer at {DateTimeOffset.UtcNow:O}");
        sb.AppendLine($"// Goal: {EscapeLineComment(trace.Goal)}");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Text;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Bitwyck.Core.Interfaces;");
        sb.AppendLine("using Bitwyck.Core.Models;");
        sb.AppendLine();
        sb.AppendLine("namespace Bitwyck.Synth;");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {className} : ITool");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IToolRegistry _registry;");
        sb.AppendLine($"    public {className}(IToolRegistry registry) {{ _registry = registry; }}");
        sb.AppendLine();
        sb.AppendLine($"    public string Name => {QuoteLiteral(toolName)};");
        sb.AppendLine($"    public string Description => {QuoteLiteral($"Synthesized skill for goal: {trace.Goal}")};");

        // Collect argument schemas from the first call if present
        var argSchema = trace.Calls.Count > 0
            ? string.Join("|", Enumerable.Range(1, trace.Calls[0].Arguments.Count).Select(i => $"arg{i}"))
            : string.Empty;
        sb.AppendLine($"    public string ArgumentSchema => {QuoteLiteral(argSchema)};");
        sb.AppendLine();
        sb.AppendLine("    public async Task<ToolResult> ExecuteAsync(IReadOnlyList<string> arguments, CancellationToken ct = default)");
        sb.AppendLine("    {");
        sb.AppendLine("        var sb = new StringBuilder();");
        sb.AppendLine("        var allOk = true;");
        sb.AppendLine();

        for (var i = 0; i < trace.Calls.Count; i++)
        {
            var call = trace.Calls[i];
            var varTool = $"t{i}";
            var varResult = $"r{i}";

            sb.AppendLine($"        // Step {i}: {EscapeLineComment(call.ToolName)}");
            sb.AppendLine($"        if (_registry.TryGet({QuoteLiteral(call.ToolName)}, out var {varTool}) && {varTool} != null)");
            sb.AppendLine("        {");

            // Build the argument array literal
            sb.Append($"            var {varResult} = await {varTool}.ExecuteAsync(new[] {{ ");
            for (var a = 0; a < call.Arguments.Count; a++)
            {
                if (a > 0) sb.Append(", ");
                sb.Append(QuoteLiteral(call.Arguments[a]));
            }
            sb.AppendLine(" }, ct);");

            sb.AppendLine($"            sb.AppendLine($\"[step {i}] \" + ({varResult}.Success ? \"OK: \" : \"FAIL: \") + ({varResult}.Success ? {varResult}.Output : {varResult}.Error));");
            sb.AppendLine($"            if (!{varResult}.Success) allOk = false;");
            sb.AppendLine("        }");
            sb.AppendLine("        else");
            sb.AppendLine("        {");
            sb.AppendLine($"            sb.AppendLine({QuoteLiteral($"[step {i}] missing tool: {call.ToolName}")});");
            sb.AppendLine("            allOk = false;");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        sb.AppendLine($"        return allOk ? ToolResult.Ok({QuoteLiteral(toolName)}, sb.ToString()) : ToolResult.Fail({QuoteLiteral(toolName)}, sb.ToString());");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// SHA-256 of the UTF-8 goal string, first 12 hex chars.
    /// </summary>
    private static string ComputeGoalHash(string goal)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(goal));
        return Convert.ToHexString(bytes)[..12].ToLowerInvariant();
    }

    /// <summary>
    /// Produces a properly escaped C# string literal (including surrounding
    /// double-quotes) using Roslyn's <c>SymbolDisplay.FormatLiteral</c>.
    /// </summary>
    private static string QuoteLiteral(string value) =>
        Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    /// <summary>Strips newlines from a value so it can appear in a // comment.</summary>
    private static string EscapeLineComment(string value) =>
        value.Replace('\r', ' ').Replace('\n', ' ');
}
